### PR TITLE
Update centres.json

### LINKED ISSUE #2: Add more Nigerian tourist centres in the centres.json file

### PR DESCRIPTION
**Pull request by DroneCodes**

### CODE REVIEW

**Comment by Johnkayode** [comment]
Hi @Fisayo-Ogunyemi You made a syntax error at the last line. Kindly fix it so I can accept your pull request

**Comment by Johnkayode** [comment]
Also, Yankari National Park is already listed

**Comment by DroneCodes** [comment]
How many more do youthink can be added?

**Comment by Johnkayode** [comment]
You can add at least 5

**Comment by DroneCodes** [comment]
Done.

You can try checking on it

**Comment by Johnkayode** [comment]
Thank you Fisayo

**Comment by DroneCodes** [comment]
😉

Would be looking forward to collaborating more.

**Pull request merged**
